### ISSUE TITLE
[Feature Request] Add a way of altering Vanilla Boss entries

### ISSUE THREAD

**Issue by MarfMaster** [JavidPack/BossChecklist#104]
This would allow for better compatibility with mods that alter vanilla progression by letting you disable the Boss entries usually provided by Boss Checklist and add your own instead.
With this you can make it clear whether any vanilla bosses have been altered and no longer fit the default Boss Checklist descriptions. 
In the case of multiple mods requesting this, perhaps adding an option to sort the priority of which mods new vanilla entries get chosen could give modpacks a lot of potential, or even allowing you to disable a given mods entries, though that's more than I'm asking for here. 
I just want to be able to rename Skeletron Prime, The Twins and move Plantera to somewhere else in progression.

**Comment by SheepishShepherd** [comment]
I have considered doing something for this. I don't like the idea of changing the base vanilla entries, however, I thought maybe we could have a mod call where the mod developer essentially creates a "vanilla" entry submission and that would be put into a list. When a player joins a world, they would have the option to choose which vanilla entry overwrite takes priority, including the base one (all of which would be client-sided). The entries would still be tied to the base entry, so the defeation check and hidden state would still functionally be shared.

A config might also be in order for this, perhaps a server based one where it would force the base entry? Maybe a prompt for the users to select from which mod would take the overwrite priority? I would like to hear your thoughts on this as well @JavidPack

**Comment by SheepishShepherd** [comment]
I don't plan on making this happen. As far as I am aware this can be done with IL editing.
