### ISSUE TITLE
Can't run Boss Checklist on server

### ISSUE THREAD

**Issue by CatWhyN0t** [JavidPack/BossChecklist#112]
An error occurred while loading BossChecklist v1.1.6.1
It has been detected that this mod was built for tModLoader v0.11.8.3

**Comment by JavidPack** [comment]
It seems you downloaded the mod from our releases page. Releases are now on steam. If you are going the route of manually downloading .tmod files, you can get them from the workshop mods folder: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#mods

Use the highest version lower than or equal to whatever version of tmod you are on.
