### ISSUE TITLE
[Feature Request] Bestiary

### ISSUE THREAD

**Issue by vavavr00m** [JavidPack/BossChecklist#128]
Bestiary will be nice with all the stats (HP, strengths and weaknesses, player debuffs, spawn duration if applicable) and comparison among the same bosses from different modes or mods - currently, it seems Hero's mod or Boss checklist doesn't have these or maybe I missed the option.

**Comment by SheepishShepherd** [comment]
Using the bestiary seems perfectly fine to get that information and adding it to the boss log doesn't seem necessary.

**Comment by vavavr00m** [comment]
Can I ask how to bring up the bestiary if it's already there?

**Comment by SheepishShepherd** [comment]
I thought you were suggesting bestiary features for the boss log?

**Comment by vavavr00m** [comment]
Bestiary for all the creatures (minions and bosses) not just the bosses. Like an advanced pokedex if that makes sense.

**Comment by JavidPack** [comment]
The bestiary is a Terraria feature added in 1.4. The button is at the bottom right of the inventory:

![image](https://github.com/JavidPack/BossChecklist/assets/4522492/1937491d-3f3a-49d9-a726-83e0c3003ede)

You can use it to view useful info of bosses and regular enemies, provided you have killed them.

![image](https://github.com/JavidPack/BossChecklist/assets/4522492/1ee76afc-5387-4c79-9806-9ebc1ab26c38)
