### ISSUE TITLE
No Boss defeat message in in-game chat/Bosses not marked as defeated on Boss Log

### ISSUE THREAD

**Issue by AexDEye9** [JavidPack/BossChecklist#137]
The title is self explanatory ^^ however...

- Boss records are still saved correctly (unsure on world record tab... will get back to that in a different issue)
![image](https://github.com/JavidPack/BossChecklist/assets/61853861/1755e33c-9ccf-424a-b09b-8724803449c6)

- On multiplayer, Hosting via the .bat file within the steam folder. Console contains...
'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (see server.log for full trace)'

Server.log file: 
[server.log](https://github.com/JavidPack/BossChecklist/files/13402853/server.log)

**Comment by AexDEye9** [comment]
Update:
After some more testing and a server restart, i can't seem to recreate this bug at all, with no evidence as to why.

**Comment by DipolarHook** [comment]
Me and my friend have the same issue and it has locked our progression. We killed lunatic cultist and the lunar event did not start.

**Comment by JavidPack** [comment]
Please post client.log and server.log from the session where you experienced the issue, dipolar

https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#logs

**Comment by SheepishShepherd** [comment]
> Update: After some more testing and a server restart, i can't seem to recreate this bug at all, with no evidence as to why.

If your world existed before the update, this makes me think that I did not change the name of the world record data beforehand. Which would load you old world record data (created even if you hadnlt enabled the feature), but it doesn't have the correct data? Restarting your world would erase the old data in place of the new data, which could be why you aren't experiencing it anymore.

In which case I will rename the player data for world records.

**Comment by DipolarHook** [comment]
Here are the requested logs.
[client.log](https://github.com/JavidPack/BossChecklist/files/13404266/client.log)
[server.log](https://github.com/JavidPack/BossChecklist/files/13404267/server.log)

**Comment by SheepishShepherd** [comment]
I looked back at some of my older worlds, and I did in fact rename the the data tag, so I will keep looking.

**Comment by SheepishShepherd** [comment]
Ah, I think I found the issue. I only have the list populate if the data exists. I forgot to populate the list when it cannot find any data to take from.
