### ISSUE TITLE
Stuck on updating in the mod browser

### ISSUE THREAD

**Issue by JuniKnytt** [JavidPack/BossChecklist#14]
On the mod, browser while downloading an update to the mod, it gets stuck at the last tick of the bar and never fully downloads.

**Comment by JavidPack** [comment]
I just checked and the file downloads fine. It might be that the file is still "open" somehow, what I would try is restarting your computer, then downloading again, if that doesn't work, post a client.log file 


```
Windows Logs: %UserProfile%\Documents\My Games\Terraria\ModLoader\Logs (This is typically found in C:\Documents\)
Linux Logs: ~/.local/share/Terraria/ModLoader/Logs/ or $XDG_DATA_HOME/Terraria/ModLoader/Logs/
Mac Logs: ~/Library/Application support/Terraria/ModLoader/Logs/```

**Comment by SheepishShepherd** [comment]
Closed for being outdated, and seemingly solved.
