### ISSUE TITLE
"View Collectibles Only" button in Boss Log causes game crash with Calamity Mod

### ISSUE THREAD

**Issue by Lunacae18** [JavidPack/BossChecklist#22]
### So after some several tests of different mods enabled/disabled, I've managed to narrow this issue down to an incompatibility with Calamity Mod, and the Boss Log menu.
In short, selecting any boss in this menu, then navigating to the "View Collectibles Only" button. Using this button causes a fatal error and thus crashes the game.

Active mods at the time of crash;

- Calamity Mod
- Calamity Mod Music
- Calamity Mod Extra Music
- Boss Checklist

[client.log](https://github.com/JavidPack/BossChecklist/files/4176502/client.log)

System: Windows

**Comment by SheepishShepherd** [comment]
Issue should be fixed next update. Reopen if this isn't the case.
