### ISSUE TITLE
Visual bug in "Boss Log" menu

### ISSUE THREAD

**Issue by Lunacae18** [JavidPack/BossChecklist#23]
It appears there is a math bleed only in the knockback stats on weapons/summons within the Boss Log menu.
Using XItemStats, I am able to watch as the values increase towards (and eventually reach) "infinity"

This appears to happen only when the player has an item/pet/mount which increases knockback.

Note: This is purely a visual bug, and does not affect gameplay in any form.

**Comment by SheepishShepherd** [comment]
The Boss Log just draws items in itemslots, which are unmodified, I dont think there is anything WE can do about this, so you may have to report this to XItemStats.
