### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [JavidPack/BossChecklist#26]
The boss log button and some elements of the log's UI are missing.
![image](https://user-images.githubusercontent.com/39163107/77486645-b1cbbd00-6e06-11ea-8bb8-67134421dfd2.png)
![image](https://user-images.githubusercontent.com/39163107/77486675-c27c3300-6e06-11ea-82b7-d697f0d8916a.png)

**Comment by SheepishShepherd** [comment]
Should be fixed with earlier UI changes, re-open if the issue arises.
