### ISSUE TITLE
Mod Auto-Disabling Itself

### ISSUE THREAD

**Issue by vizthex123** [JavidPack/BossChecklist#3]
Like the title says, the mod keeps auto-disabling itself. I'm using tModLoader v0.11.3, and I'm thinking this mod just hasn't fully updated yet or something.

I also get the occasional random crash caused by this mod (but forgot to screenshot it, so I'll attach one if it happens again)

Do you think you can fix it? This is one of my favourite QoL mods ever, and I'd rather not have to get rid of it.

**Comment by JavidPack** [comment]
I'll need the logs to help you.

**Comment by vizthex123** [comment]
Alright, I've changed my pack since this happened and it seems to have stopped, but this should be the right one: (If not tell me)

[2019-07-23-24.zip](https://github.com/JavidPack/BossChecklist/files/3483665/2019-07-23-24.zip)

**Comment by vizthex123** [comment]
Updated; It happened again (and crashed the game this time), here's the new log:

[2019-07-23-32.zip](https://github.com/JavidPack/BossChecklist/files/3487096/2019-07-23-32.zip)

**Comment by JavidPack** [comment]
Thanks, I'll look into it. Was the game out of focus at the time?
