### ISSUE TITLE
Spirit Mod bosses have no description

### ISSUE THREAD

**Issue by thedragonslayr** [JavidPack/BossChecklist#31]
![Screenshot_8](https://user-images.githubusercontent.com/40613094/83936790-1fd81d00-a784-11ea-8e28-671a0f147f47.png)

Pages like this appear for all spirit mode bosses but Thorium and Calamity work just fine.

**Comment by JavidPack** [comment]
That's up to spirit mod developers to add. Pretty sure the mod is abandoned though.

**Comment by thedragonslayr** [comment]
but here https://forums.terraria.org/index.php?threads/boss-checklist-in-game-progression-checklist.50668/ it says in the changelog spritmod was supported on march 6th 2017

**Comment by JavidPack** [comment]
Yes, that was back when boss checklist itself added support, now it's up to the mods to add support, and spirit hasn't updated since boss checklist updated to 1.0, so they'll need to if they want all the features. I'll fix the changelog
