### ISSUE TITLE
Brain of Cthulhu not listed?

### ISSUE THREAD

**Issue by ltlvxn** [JavidPack/BossChecklist#36]
Is it a bug or am I missing something?

**Comment by JavidPack** [comment]
Are you sure you aren't in a corruption world?

**Comment by SheepishShepherd** [comment]
Brain of Cthulhu does appear on the Boss List if the world is crimson. You can have the Brain of Cthulhu listed (while its not already defeated) by enabling the ModConfig "Hide unavailable and hidden bosses".
