### ISSUE TITLE
Modded Event Enemies

### ISSUE THREAD

**Issue by SmashMania13** [JavidPack/BossChecklist#38]
I'm not sure if this is intentional or not but modded enemies from vanilla events aren't showing up. ex: goblin trapper, goblin drummer from Thorium.

**Comment by JavidPack** [comment]
That would be up to those modders adding them via the AddToEventNPCs Mod.Call. If they did code that up, and it's not working, let us know and we'll look into it.

**Comment by SheepishShepherd** [comment]
Confirmed to just be not added in ModCalls. Thorium should be adding it in a future update.
