### ISSUE TITLE
vanilla event name rewrite

### ISSUE THREAD

**Issue by sigangzzang** [JavidPack/BossChecklist#41]
can add some write(display) a vanilla event name list? use localizer mod, can't change event name. (blood moon/solar eclipse/lunar event) i found only event load, if rewrite here, checklist is broken.

There is no event name entry in the tmodloader localization file too. so all name changed, but not event name.

(terraria not support korean. so korea player use en-US rewrite patcher and font dump. so mod localization add is impossible. only can use localizer mod.)

**Comment by SheepishShepherd** [comment]
Outdated, may have been resolved though.
