### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Kyloman** [JavidPack/BossChecklist#44]
Around half the time I use this mod, I get missing UI elements (icon to open, check marks, buttons). 
![BossLog1](https://user-images.githubusercontent.com/12413494/121984776-71789780-cd48-11eb-94b1-a359b7ba16c4.PNG)
![Bosslog2PNG](https://user-images.githubusercontent.com/12413494/121984779-73425b00-cd48-11eb-86b6-0cd0b9be2d6f.PNG)

**Comment by SheepishShepherd** [comment]
Mentioned in issue #42 and will be 'fixed' next update once final additions are tested. Sorry for the late response.
