### ISSUE TITLE
Feature Request: Allows modders to access the boss portrait

### ISSUE THREAD

**Issue by DanYami** [JavidPack/BossChecklist#48]
Recently, Starlight River did this: 
![image](https://cdn.discordapp.com/attachments/556368841689792523/910092895724404806/Dark.gif)

This required a bit of IL editing.

Me and a few others think allowing modders to access the drawing of the boss portrait so we can apply shaders, draw our own things (for multibosses or bosses made out of segments) and other things people may come up with

![image](https://user-images.githubusercontent.com/32519717/142646103-41ab9c19-2a95-4601-b892-5bd2fb542b1c.png)
![image](https://user-images.githubusercontent.com/32519717/142646165-c42af957-c505-4e98-92f0-9b1d6e8d0cde.png)

**Comment by SheepishShepherd** [comment]
@DanYami Update has been released with this feature. Try it out and let us know if anything else is needed.

**Comment by SheepishShepherd** [comment]
No confirmation on the feature being fully complete, but since this issue post is almost 4 months old I think it is safe to assume all is in order.
