### ISSUE TITLE
Boss Log randomly going to index in multiplay

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/BossChecklist#5]
Report from forum:

In multiplayer, everytime you click someone in the book or scroll down it resets the input back to the default (so If I click on a boss his loot it will boot me back to the list of bosses after about 2 seconds). However I tried the mod on singleplayer and it works totally as expected ! Is this a known issue ?

**Comment by roboderpy** [comment]
[i can confirm](https://i.dbotthepony.ru/Videos/2019-12-24%2022-18-22.mp4)
