### ISSUE TITLE
Boss Checklist Crashes on Latest Version of tModloader (v0.11.6.1)

### ISSUE THREAD

**Issue by DeltaJordan** [JavidPack/BossChecklist#6]
Crashes on my friend's client, but doesn't crash on my computer. Seems to be something to do with a texture.

Log for the crash:
[client.log](https://github.com/JavidPack/BossChecklist/files/4000143/client.log)

**Comment by roboderpy** [comment]
seems to be an issue with newer tmodloader. Can you try 11.5?

**Comment by DeltaJordan** [comment]
I realize that it works on an older version of tModloader, I'm reporting this so it can be fixed for the latest version. My friend and I can play without it for now while we wait for it to be fixed since its not really an essential mod.

**Comment by Crazor** [comment]
Crashes on 11.6.2 for me, too. Works fine on 11.5

**Comment by VVV101** [comment]
This happens in log during crash.
`[22:40:41] [8/INFO] [StatusText]: Validating world save
[22:40:41] [8/WARN] [tML]: Silently Caught Exception: 
System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_17(BinaryWriter w, String v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress)
   в Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave)
   в Terraria.IO.WorldFile.saveWorld(Boolean useCloudSaving, Boolean resetTime)
   в Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[22:40:41] [8/ERROR] [tML]: Unhandled Exception
System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_17(BinaryWriter w, String v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress)
   в Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave)
   в Terraria.IO.WorldFile.saveWorld(Boolean useCloudSaving, Boolean resetTime)
   в Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by VVV101** [comment]
This happens in log during crash on tModloader 0.11.6.2.
```
[22:40:41] [8/INFO] [StatusText]: Validating world save
[22:40:41] [8/WARN] [tML]: Silently Caught Exception: 
System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_17(BinaryWriter w, String v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress)
   в Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave)
   в Terraria.IO.WorldFile.saveWorld(Boolean useCloudSaving, Boolean resetTime)
   в Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[22:40:41] [8/ERROR] [tML]: Unhandled Exception
System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_17(BinaryWriter w, String v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList`1 list)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_21(BinaryWriter w, IList v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__20_24(BinaryWriter w, TagCompound v)
   в Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v)
   в Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w)
   в Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress)
   в Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave)
   в Terraria.IO.WorldFile.saveWorld(Boolean useCloudSaving, Boolean resetTime)
   в Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by SheepishShepherd** [comment]
Closed for being outdated.
