### ISSUE TITLE
[Feature Request] Mod Call support for Day Despawners

### ISSUE THREAD

**Issue by Lurrae** [JavidPack/BossChecklist#61]
At the moment, all modded bosses who despawn during daytime in a similar manner to Eye of Cthulhu will use the default "[boss] is no longer after you..." message, instead of the "[boss] flees as the sun rises..." message that the Eye of Cthulhu, Twins, and Destroyer use. Personally, I feel that for consistency's sake, there should be some way to add more NPCs to the list of NPCs that use the day despawning message.
There are two potential ways this could be addressed; either the existing "AddBossWithInfo" call is updated to have a bool for whether the boss despawns during the day or not. If that bool is true, they're added to the DayDespawners list automatically, or make a new call type:
`BossChecklist.Call("AddDayDespawners", NPCType<MyCoolNightBoss>())`
This example of the new call function would be used to add `MyCoolNightBoss` to the list of day despawners. "AddDayDespawners" could also optionally support using a `List<int>` instead of a singular int in case modders have several bosses to add, but either way works.

**Comment by SheepishShepherd** [comment]
Thank you for proposing this issue. The despawn messages have been fairly low down in the priority list, but I'll be more than happy to take the idea and expand on it. Current plan is to do the mod call you mentioned and set up multiple messages with different conditions. So more despawn messages can be made than just daylight despawns, such as killing all players, under a specific gamemode, etc.
