### ISSUE TITLE
Simplify the wiki

### ISSUE THREAD

**Issue by ItsSmudgy** [JavidPack/BossChecklist#77]
I want to make my mod's bosses show up on the Boss Checklist, but idk how. Could you **_please_** simplify the tutorial on how to do that so my peanut sized brain can understand what to do?

**Comment by SheepishShepherd** [comment]
What are you having issues understanding? The Mod call is explained thoroughly, at least as much as I could.

**Comment by SheepishShepherd** [comment]
No further explanation. Wiki is well detailed so I'm not sure where the misunderstanding is.
