### ISSUE TITLE
Defeating one world evil boss incorrectly reports both as beaten on drunk worlds

### ISSUE THREAD

**Issue by Hexicube** [JavidPack/BossChecklist#82]
When playing on a drunk world, defeating one of the two world evil bosses (in my case, BoC) reports the other (EoW) as also beaten despite having not done so.

**Comment by JavidPack** [comment]
The game tracks them as a single boss, `NPC.downedBoss2`, because the game doesn't expect you to fight both. If you'd like to fight both, you'll just have to remember not to skip the alternate boss.
