### ISSUE TITLE
We need to clear out bools in PreWorldGen too

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/BossChecklist#83]
From forum: "For some reason when i make a new world some bosses i haven't beaten are checked out, the only mod i have that adds bosses is calamity. The first world i made had all the calamity bosses that i had beaten in a different world checked out, and when i made a second world the torch god, blood moon and solar eclipse were checked out."

OnWorldLoad isn't called when generating a world, so data from a previous world loaded will be saved to the new world when that world finishes generating

**Comment by SheepishShepherd** [comment]
Measures have been made to resolve this. Reopen if issue persists.
