### ISSUE TITLE
Whether to support the api in http mode

### ISSUE THREAD

**Issue by x0620x** [JavidPack/BossChecklist#86]
Hi, I love this mod
Do you support the API in http mode to view defeated bosses and undefeated bosses?
If not, whether to consider adding this API later

**Comment by JavidPack** [comment]
I'm not sure what you mean, can you explain this idea?

**Comment by x0620x** [comment]
Hello author, I mean when loading a module, can you start a http service locally, and you can use this service to query defeated and undefeated bosses

E.g:http:127.0.0.1:port/boss
returned messages
status=200
defeated：king slime、
undefeated：Eye of Crusus、world eater、

**Comment by x0620x** [comment]
no

**Comment by JavidPack** [comment]
I don't really know how to make that, but maybe someone would implement that as a separate mod.

**Comment by x0620x** [comment]
thank you for your reply. I am trying to make an interface. I found that by querying the boss list on the server side, the console boss list can be colored to differentiate between defeated and undefeated ones.
Is it possible to add a text mark to this? instead of distinguishing by color
<img src="https://img-1259793745.itggg.cn/img-1259793745QQ截图20221104111351.jpg" style="zoom:33%;" />


**like this**
Boss: Queen Bee(defeated)
Boss: Skeletron(undefeated)
Boss: Turkor The Ungrateful(undefeated)
Boss: Deerclops(defeated)
Boss: Deviantt(defeated)

**Comment by JavidPack** [comment]
If you are making a mod, use the https://github.com/JavidPack/BossChecklist/blob/1.4/BossChecklistIntegrationExample.cs integration code to retrieve the boss data directly, then you can do whatever you want with the resulting data.
